server:
  port: 1111

spring:
  application:
    name: STOCK-PRICE-APP
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: STOCK-DATABASE

logging:
  file:
    path: /var/tmp/
    name: /var/tmp/mylog.log
    

    


  
    
       
#  datasource:
#    u  sername: sa
#    password: sa
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#  jpa:
#    defer-datasource-initialization: true 
#    show-sql: true
    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9090/eureka
#      