INSERT INTO STOCK_PRICE_DTLS(STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES (101,'TCS', 3000.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES (102,'HCL', 500.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES (103,'AXIS', 4500.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES (104,'SBI', 450.00);

