server:
  port: 2222
spring:
  application:
    name: STOCK-CALC-API
  cloud:
    config:
      enabled: false

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9090/eureka
      

    